services:
  superset:
    build:
      context: ./superset
      dockerfile: Dockerfile
    restart: always
    environment:
      ADMIN_USERNAME: admin
      ADMIN_EMAIL: admin@admin.com
      ADMIN_PASSWORD: admin
    ports:
      - 8080:8088
    volumes:
      - ./superset_home:/app/superset_home
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8088/health" ]
      interval: 2s
      timeout: 60s
      retries: 20
    depends_on:
      warehouse:
        condition: service_healthy
  pgadmin:
    image: dpage/pgadmin4:9.1.0
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      warehouse:
        condition: service_healthy
    ports:
      - "5050:80"
    restart: always
  warehouse:
    image: postgres:13
    environment:
      POSTGRES_USER: warehouse
      POSTGRES_PASSWORD: warehouse
      POSTGRES_DB: warehouse
    ports:
      - 5432:5432
    volumes:
      - warehouse-postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "warehouse" ]
      interval: 5s
      retries: 30
      start_period: 5s
    restart: always

volumes:
  warehouse-postgres-db-volume:
